@extends('layouts.master-without-nav')
@section('title', 'Masuk - Sistem Informasi Digital LP. Ma\'arif NU PWNU DIY')
@section('css')
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
@if(config('services.turnstile.enabled') && filled(config('services.turnstile.site_key')))<link rel="preconnect" href="https://challenges.cloudflare.com"><script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>@endif
<style>
:root{--login-green:#00745a;--login-green-light:#009071;--login-green-dark:#00553f;--login-ink:#172a24;--login-muted:#6d7f7d;--login-border:#dce7e3;--login-surface:#f4f8f6}html,body{min-height:100%;margin:0;font-family:'Poppins',sans-serif;background:#e9f2ef}*,*::before,*::after{box-sizing:border-box}
.web-login-page{min-height:100vh;display:grid;place-items:center;position:relative;overflow:hidden;padding:42px;background:radial-gradient(circle at 13% 12%,rgba(0,144,113,.22),transparent 27%),radial-gradient(circle at 87% 86%,rgba(0,85,63,.15),transparent 26%),linear-gradient(145deg,#edf6f3 0%,#f8fbfa 48%,#e5f0ec 100%)}
.web-login-page::before{content:'';position:absolute;inset:0;pointer-events:none;opacity:.35;background-image:linear-gradient(rgba(0,85,63,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(0,85,63,.08) 1px,transparent 1px);background-size:34px 34px;mask-image:linear-gradient(to bottom,#000,transparent 76%)}
.login-layout{width:min(1120px,100%);min-height:690px;display:grid;grid-template-columns:minmax(0,1.15fr) minmax(410px,.85fr);position:relative;z-index:1;overflow:hidden;border:8px solid rgba(255,255,255,.9);border-radius:34px;background:#fff;box-shadow:0 30px 80px rgba(23,42,36,.18)}
.journey-panel{min-height:100%;display:flex;flex-direction:column;position:relative;overflow:hidden;padding:48px 46px 38px;color:#fff;border-radius:26px;isolation:isolate;background:radial-gradient(circle at 76% 27%,rgba(66,210,171,.8),transparent 34%),radial-gradient(circle at 16% 78%,rgba(0,85,63,.72),transparent 38%),linear-gradient(145deg,var(--login-green-dark),var(--login-green-light))}
.journey-panel::before,.journey-panel::after{content:'';position:absolute;z-index:-1;border-radius:50%;filter:blur(4px);opacity:.52}.journey-panel::before{width:360px;height:360px;top:-190px;left:-120px;background:#2ec59b}.journey-panel::after{width:430px;height:430px;right:-250px;bottom:-230px;background:#004b39}
.journey-brand{width:178px;min-height:54px;display:flex;align-items:center;padding:8px 14px;border-radius:14px;background:rgba(255,255,255,.94);box-shadow:0 12px 28px rgba(0,49,37,.16)}.journey-brand img{display:block;width:100%;height:auto}.journey-copy{margin-top:auto;padding-top:74px}
.journey-kicker{display:inline-flex;align-items:center;gap:8px;margin-bottom:18px;padding:9px 15px;border:1px solid rgba(255,255,255,.16);border-radius:999px;color:#fff;background:rgba(255,255,255,.14);backdrop-filter:blur(10px);font-size:.79rem;font-weight:500}.journey-title{margin:0 0 10px;color:#fff;font-size:clamp(2.25rem,4vw,3.35rem);font-weight:500;line-height:1.08;letter-spacing:-.045em}.journey-description{margin:0;color:rgba(255,255,255,.82);font-size:.94rem;line-height:1.65}
.journey-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:38px}.journey-step{min-height:132px;display:flex;flex-direction:column;justify-content:space-between;padding:15px;border:1px solid rgba(255,255,255,.14);border-radius:18px;color:rgba(255,255,255,.86);background:rgba(255,255,255,.11);backdrop-filter:blur(10px);font-size:.73rem;line-height:1.35}.journey-step.is-active{color:var(--login-ink);background:rgba(255,255,255,.95)}.step-number{width:27px;height:27px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.4);border-radius:50%;color:#fff;font-size:.72rem;font-weight:600}.is-active .step-number{border-color:var(--login-green);color:#fff;background:var(--login-green)}
.form-panel{display:flex;align-items:center;justify-content:center;padding:54px 56px;background:#fff}.form-inner{width:100%;max-width:390px}.form-eyebrow{margin:0 0 8px;color:var(--login-green);font-size:.74rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.form-title{margin:0;color:var(--login-ink);font-size:2.05rem;font-weight:600;line-height:1.2;letter-spacing:-.04em}.form-subtitle{margin:10px 0 32px;color:var(--login-muted);font-size:.82rem;line-height:1.6}
.status-alert{margin-bottom:16px;padding:11px 13px;border:1px solid;border-radius:12px;font-size:.75rem;line-height:1.45}.status-alert.success{border-color:#bfe8cb;color:#1d6b40;background:#e8f8ee}.status-alert.error{border-color:#f7c4c4;color:#a33b3b;background:#fdecec}.auth-field-group{margin-bottom:18px}.input-label{display:block;margin-bottom:8px;color:var(--login-ink);font-size:.75rem;font-weight:600}
.field-shell{min-height:52px;display:flex;align-items:center;overflow:hidden;border:1px solid transparent;border-radius:13px;background:var(--login-surface);transition:border-color .2s,box-shadow .2s,background .2s}.field-shell:focus-within{border-color:var(--login-green);background:#fff;box-shadow:0 0 0 4px rgba(0,116,90,.1)}.field-icon{width:48px;flex:0 0 48px;display:grid;place-items:center;color:#78918a}.field-icon svg,.toggle-password svg{width:18px;height:18px;fill:currentColor}
.input-control{width:100%;min-height:50px;border:0;outline:0;color:var(--login-ink);background:transparent;font:500 .78rem/1.4 'Poppins',sans-serif}.input-control::placeholder{color:#9aaba6;font-weight:400}.input-control:-webkit-autofill{-webkit-text-fill-color:var(--login-ink);-webkit-box-shadow:0 0 0 1000px var(--login-surface) inset}.toggle-password{width:44px;height:44px;flex:0 0 44px;display:grid;place-items:center;border:0;color:#78918a;background:transparent;cursor:pointer}.toggle-password:hover{color:var(--login-green)}.field-error{margin-top:6px;color:#b93434;font-size:.69rem;line-height:1.4}
.form-actions{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:-2px 0 21px;font-size:.72rem}.remember-check{display:inline-flex;align-items:center;gap:8px;color:var(--login-muted);cursor:pointer}.remember-check input{width:16px;height:16px;margin:0;accent-color:var(--login-green)}.forgot-link,.back-link{color:var(--login-green);font-weight:600;text-decoration:none}.forgot-link:hover,.back-link:hover{color:var(--login-green-dark);text-decoration:underline}.turnstile-wrap{display:flex;justify-content:center;margin:0 0 18px}.turnstile-wrap .cf-turnstile{max-width:100%}
.submit-btn{width:100%;min-height:52px;border:0;border-radius:13px;color:#fff;background:linear-gradient(135deg,var(--login-green-light),var(--login-green-dark));box-shadow:0 13px 26px rgba(0,116,90,.22);font:600 .84rem/1 'Poppins',sans-serif;cursor:pointer;transition:transform .2s,box-shadow .2s}.submit-btn:hover{transform:translateY(-1px);box-shadow:0 16px 30px rgba(0,116,90,.28)}.submit-btn:focus-visible,.toggle-password:focus-visible,.forgot-link:focus-visible,.back-link:focus-visible{outline:3px solid rgba(0,116,90,.24);outline-offset:3px}.form-footer{margin:19px 0 0;text-align:center;color:var(--login-muted);font-size:.7rem;line-height:1.5}
@media(max-width:900px){.web-login-page{align-items:start;padding:24px}.login-layout{min-height:auto;grid-template-columns:1fr;max-width:620px}.journey-panel{min-height:auto;padding:30px;border-radius:26px 26px 20px 20px}.journey-copy{padding-top:44px}.journey-title{font-size:2.3rem}.journey-steps{margin-top:26px}.journey-step{min-height:105px}.form-panel{padding:46px 42px 50px}}
@media(max-width:560px){.web-login-page{display:block;padding:0;background:#fff}.web-login-page::before{display:none}.login-layout{width:100%;border:0;border-radius:0;box-shadow:none}.journey-panel{padding:24px 22px 28px;border-radius:0 0 28px 28px}.journey-brand{width:150px;min-height:48px}.journey-copy{padding-top:34px}.journey-kicker,.journey-description,.journey-steps{display:none}.journey-title{margin:0;font-size:1.75rem}.form-panel{align-items:flex-start;padding:38px 22px 42px}.form-title{font-size:1.75rem}}
</style>
@endsection
@section('content')
@php
$isSpmbHost=request()->getHost()==='spmb.nuist.id';
$loginAction=$isSpmbHost?url('/login'):route('login');
$forgotPasswordUrl=$isSpmbHost?url('/password/reset'):route('mobile.password.request');
$backUrl=$isSpmbHost?url('/'):route('landing');
@endphp
@include('mobile._auth-loader')
<div class="web-login-page"><main class="login-layout" aria-labelledby="login-title">
<section class="journey-panel" aria-labelledby="journey-title">
<a class="journey-brand" href="{{ $backUrl }}" aria-label="Kembali ke halaman utama NUIST"><img src="{{ asset('images/logo1.png') }}" alt="NUIST"></a>
<div class="journey-copy"><span class="journey-kicker">Selamat datang kembali <span aria-hidden="true">👋</span></span><p class="journey-description">Akses layanan pendidikan digital LP. Ma'arif NU PWNU DIY dalam satu tempat.</p>
<div class="journey-steps" aria-label="Tahapan akses NUIST"><div class="journey-step is-active"><span class="step-number">1</span><span>Masuk ke akun Anda</span></div><div class="journey-step"><span class="step-number">2</span><span>Akses layanan sesuai peran</span></div><div class="journey-step"><span class="step-number">3</span><span>Kelola data lebih mudah</span></div></div></div>
</section>
<section class="form-panel"><div class="form-inner"><p class="form-eyebrow">NUIST.ID</p><h1 class="form-title" id="login-title">Masuk</h1><p class="form-subtitle">{{ $isSpmbHost?'Masuk sebagai Admin Sekolah untuk mengelola dashboard SPMB.':'Gunakan akun Anda untuk mengakses seluruh layanan NUIST.' }}</p>
@if(session('status'))<div class="status-alert success" role="status">{{ session('status') }}</div>@endif
@if(session('error'))<div class="status-alert error" role="alert">{{ session('error') }}</div>@endif
<form method="POST" action="{{ $loginAction }}">@csrf
<div class="auth-field-group"><label class="input-label" for="email">Email</label><div class="field-shell"><span class="field-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M20 4H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2Zm0 4-8 5-8-5V6l8 5 8-5Z"/></svg></span><input id="email" name="email" type="email" class="input-control" value="{{ old('email') }}" placeholder="nama@email.com" autocomplete="email" required autofocus></div>@error('email')<div class="field-error" role="alert">{{ $message }}</div>@enderror</div>
<div class="auth-field-group"><label class="input-label" for="password">Password</label><div class="field-shell"><span class="field-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M17 8h-1V6a4 4 0 0 0-8 0v2H7a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-8a2 2 0 0 0-2-2Zm-5 8a2 2 0 1 1 2-2 2 2 0 0 1-2 2Zm-2-8V6a2 2 0 0 1 4 0v2Z"/></svg></span><input id="password" name="password" type="password" class="input-control" placeholder="Masukkan password" autocomplete="current-password" required><button type="button" class="toggle-password" id="togglePassword" aria-label="Tampilkan password" aria-pressed="false"><svg viewBox="0 0 24 24"><path d="M12 5c5.33 0 9.73 3.61 11 7-1.27 3.39-5.67 7-11 7S2.27 15.39 1 12c1.27-3.39 5.67-7 11-7Zm0 2C8.08 7 4.72 9.37 3.34 12 4.72 14.63 8.08 17 12 17s7.28-2.37 8.66-5C19.28 9.37 15.92 7 12 7Zm0 2.5A2.5 2.5 0 1 1 9.5 12 2.5 2.5 0 0 1 12 9.5Z"/></svg></button></div>@error('password')<div class="field-error" role="alert">{{ $message }}</div>@enderror</div>
<div class="form-actions"><label class="remember-check"><input type="checkbox" name="remember" value="1" {{ old('remember')?'checked':'' }}><span>Ingat saya</span></label><a href="{{ $forgotPasswordUrl }}" class="forgot-link">Lupa Password?</a></div>
@if(config('services.turnstile.enabled') && filled(config('services.turnstile.site_key')))<div class="turnstile-wrap"><div class="cf-turnstile" data-sitekey="{{ config('services.turnstile.site_key') }}" data-action="login" data-theme="light" data-size="normal" data-appearance="always"></div></div>@error('turnstile')<div class="field-error" role="alert">{{ $message }}</div>@enderror @endif
<button class="submit-btn" type="submit">Masuk ke NUIST</button></form>
<p class="form-footer"><a href="{{ $backUrl }}" class="back-link">{{ $isSpmbHost?'Kembali ke Halaman SPMB':'Kembali ke Halaman Utama' }}</a><br>NUIST Desktop &middot; LP. Ma'arif NU PWNU DIY</p>
</div></section></main></div>
@endsection
@section('script-bottom')
@include('mobile._auth-loader-script')
<script>document.addEventListener('DOMContentLoaded',function(){var i=document.getElementById('password'),b=document.getElementById('togglePassword');if(!i||!b)return;b.addEventListener('click',function(){var v=i.type==='text';i.type=v?'password':'text';b.setAttribute('aria-pressed',v?'false':'true');b.setAttribute('aria-label',v?'Tampilkan password':'Sembunyikan password')})});</script>
@endsection
