<div class="row g-2">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$member?->exists && isset($teachers)): ?>
<div class="col-12"><label class="form-label" for="existing_user_id">Pilih akun tenaga pendidik yang sudah ada (opsional)</label><select class="form-select" id="existing_user_id" name="existing_user_id" onchange="bppFillTeacher(this)"><option value="">Tambah akun baru</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $teachers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $teacher): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?><?php ($schoolName = optional($teacher->madrasah)->name ?: (optional($teacher->madrasahTambahan)->name ?: $teacher->instansi_asal)); ?><option value="<?php echo e($teacher->id); ?>" data-name="<?php echo e($teacher->name); ?>" data-email="<?php echo e($teacher->email); ?>" data-jabatan="<?php echo e($teacher->jabatan ?: $teacher->ketugasan); ?>" data-instansi="<?php echo e($schoolName); ?>"><?php echo e($teacher->name); ?> · <?php echo e($teacher->email); ?> · <?php echo e($schoolName ?: 'Madrasah belum diatur'); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select><small class="text-muted">Instansi asal otomatis mengambil nama madrasah/sekolah akun tenaga pendidik.</small></div>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['name'=>'Nama','email'=>'Email','jabatan'=>'Jabatan','instansi_asal'=>'Instansi Asal']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?>
<div class="col-md-6"><label class="form-label" for="member-<?php echo e($member?->id ?? 'new'); ?>-<?php echo e($field); ?>"><?php echo e($label); ?></label><input id="member-<?php echo e($member?->id ?? 'new'); ?>-<?php echo e($field); ?>" name="<?php echo e($field); ?>" type="<?php echo e($field === 'email' ? 'email' : 'text'); ?>" class="form-control" value="<?php echo e($field === 'jabatan' ? ($member?->bpppmnu_jabatan ?: $member?->jabatan) : ($field === 'instansi_asal' ? ($member?->bpppmnu_instansi_asal ?: $member?->instansi_asal) : $member?->$field)); ?>" <?php if(in_array($field,['name','email'])): echo 'required'; endif; ?>></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
<div class="col-md-6"><label class="form-label">Status akun<select name="is_active" class="form-select"><option value="1" <?php if(!$member || $member->is_active): echo 'selected'; endif; ?>>Aktif</option><option value="0" <?php if($member && !$member->is_active): echo 'selected'; endif; ?>>Nonaktif</option></select></label></div>
<div class="col-md-6 password-fields"><label class="form-label"><?php echo e($member ? 'Reset password (kosongkan jika tetap)' : 'Password awal'); ?><input name="password" type="password" class="form-control" autocomplete="new-password" minlength="8" <?php if(!$member): echo 'required'; endif; ?>></label></div>
<div class="col-md-6 password-fields"><label class="form-label">Konfirmasi password<input name="password_confirmation" type="password" class="form-control" autocomplete="new-password" minlength="8" <?php if(!$member): echo 'required'; endif; ?>></label></div>
<div class="col-12"><small class="text-muted">Password minimal 8 karakter: huruf besar, huruf kecil, angka, dan simbol (@$!%*?&).</small></div>
<div class="col-12"><button class="btn btn-primary mt-2">Simpan Pengurus</button></div></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$member?->exists && isset($teachers)): ?><script>window.bppFillTeacher=function(select){const o=select.options[select.selectedIndex];['name','email','jabatan','instansi_asal'].forEach(f=>{const i=document.getElementById('member-new-'+f);if(i)i.value=o?.dataset?.[f]||'';});document.querySelectorAll('.password-fields input').forEach(i=>{i.required=!select.value;i.closest('.password-fields').style.display=select.value?'none':'';});};</script><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php /**PATH /Users/lpmnudiymacpro/Documents/Project Nuist/nuist/resources/views/admin/bpppmnu/member-fields.blade.php ENDPATH**/ ?>