<div class="row g-2">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['name'=>'Nama','email'=>'Email','jabatan'=>'Jabatan','instansi_asal'=>'Instansi Asal']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?>
<div class="col-md-6"><label class="form-label" for="member-<?php echo e($member?->id ?? 'new'); ?>-<?php echo e($field); ?>"><?php echo e($label); ?></label><input id="member-<?php echo e($member?->id ?? 'new'); ?>-<?php echo e($field); ?>" name="<?php echo e($field); ?>" type="<?php echo e($field === 'email' ? 'email' : 'text'); ?>" class="form-control" value="<?php echo e($member?->$field); ?>" <?php if(in_array($field,['name','email'])): echo 'required'; endif; ?>></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
<div class="col-md-6"><label class="form-label">Status akun<select name="is_active" class="form-select"><option value="1" <?php if(!$member || $member->is_active): echo 'selected'; endif; ?>>Aktif</option><option value="0" <?php if($member && !$member->is_active): echo 'selected'; endif; ?>>Nonaktif</option></select></label></div>
<div class="col-md-6"><label class="form-label"><?php echo e($member ? 'Reset password (kosongkan jika tetap)' : 'Password awal'); ?><input name="password" type="password" class="form-control" autocomplete="new-password" minlength="8" <?php if(!$member): echo 'required'; endif; ?>></label></div>
<div class="col-md-6"><label class="form-label">Konfirmasi password<input name="password_confirmation" type="password" class="form-control" autocomplete="new-password" minlength="8" <?php if(!$member): echo 'required'; endif; ?>></label></div>
<div class="col-12"><small class="text-muted">Password minimal 8 karakter: huruf besar, huruf kecil, angka, dan simbol (@$!%*?&).</small></div>
<div class="col-12"><button class="btn btn-primary mt-2">Simpan Pengurus</button></div></div>
<?php /**PATH /Users/lpmnudiymacpro/Documents/Project Nuist/nuist/resources/views/admin/bpppmnu/member-fields.blade.php ENDPATH**/ ?>