<?php $__env->startSection('bpp-content'); ?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<div class="card"><div class="card-body"><h2><?php echo e($event->name); ?></h2><span class="badge bg-secondary"><?php echo e($event->status); ?></span>
<?php echo $__env->make('bpppmnu.event-details', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event->attachment): ?><a class="btn btn-outline-secondary btn-sm mb-3" href="<?php echo e(route('admin.bpppmnu.events.attachment', $event)); ?>">Unduh lampiran</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<div class="d-flex gap-2 flex-wrap">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(!$event->isLocked() && $event->status !== 'cancelled'): ?><a class="btn btn-outline-primary" href="<?php echo e(route('admin.bpppmnu.events.edit', $event)); ?>">Edit Agenda & Undangan</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event->status === 'draft'): ?><form method="post" action="<?php echo e(route('admin.bpppmnu.events.publish', $event)); ?>"><?php echo csrf_field(); ?><button class="btn btn-success">Terbitkan</button></form><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event->status === 'published' && now()->lte($event->attendance_close_at)): ?>
<form method="post" action="<?php echo e(route('admin.bpppmnu.events.qr', $event)); ?>"><?php echo csrf_field(); ?><button class="btn btn-primary">Generate & Tampilkan QR Baru</button></form>
<form method="post" action="<?php echo e(route('admin.bpppmnu.events.revoke', $event)); ?>" onsubmit="return confirm('Cabut semua QR aktif kegiatan ini?')"><?php echo csrf_field(); ?><button class="btn btn-outline-warning">Cabut QR</button></form>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event->status !== 'cancelled' && !$event->isFinished() && $recap['present'] === 0): ?>
<form method="post" action="<?php echo e(route('admin.bpppmnu.events.cancel', $event)); ?>" onsubmit="return confirm('Batalkan kegiatan ini?')"><?php echo csrf_field(); ?><button class="btn btn-outline-danger">Batalkan Kegiatan</button></form>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div></div></div>
<?php if($event->status === 'published' && now()->betweenIncluded($event->attendance_open_at, $event->attendance_close_at)): ?>
<div class="card"><div class="card-body">
<h3 class="h5">Scan Barcode Peserta</h3><p class="text-muted small">Arahkan kamera ke barcode identitas pengurus yang terdaftar dalam agenda ini.</p>
<video id="bpp-member-video" class="w-100 rounded bg-dark" style="max-height:320px" muted playsinline hidden></video>
<div id="bpp-member-status" class="alert alert-secondary py-2" role="status">Kamera belum dibuka.</div>
<button type="button" id="bpp-member-start" class="btn btn-primary">Buka Kamera</button>
<button type="button" id="bpp-member-stop" class="btn btn-outline-secondary" hidden>Tutup Kamera</button>
</div></div>
<script src="<?php echo e(asset('vendor/jsqr/jsQR.js')); ?>"></script>
<script>
(()=>{const v=document.getElementById('bpp-member-video'),s=document.getElementById('bpp-member-status'),b=document.getElementById('bpp-member-start'),x=document.getElementById('bpp-member-stop');let stream,timer,busy=false;const c=document.createElement('canvas'),g=c.getContext('2d',{willReadFrequently:true});const msg=(t,ok=false)=>{s.textContent=t;s.className='alert py-2 '+(ok?'alert-success':'alert-secondary')};const stop=()=>{clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;v.srcObject=null;v.hidden=true;x.hidden=true;b.disabled=false};const tick=async()=>{if(!stream||busy)return;if(v.readyState>=2){c.width=Math.min(v.videoWidth,800);c.height=Math.round(v.videoHeight*c.width/v.videoWidth);g.drawImage(v,0,0,c.width,c.height);const q=window.jsQR(g.getImageData(0,0,c.width,c.height).data,c.width,c.height,{inversionAttempts:'dontInvert'});if(q){busy=true;stop();msg('Mencatat presensi…');try{const r=await fetch('<?php echo e(route('admin.bpppmnu.events.scan-member',$event)); ?>',{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':'<?php echo e(csrf_token()); ?>'},body:JSON.stringify({nuist_id:q.data.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Barcode tidak dapat diproses.');msg(d.message+' '+d.name+' · '+d.attended_at,true);if(window.Swal)Swal.fire({icon:'success',title:'Presensi berhasil',text:d.message+' '+d.name,confirmButtonText:'OK',confirmButtonColor:'#00553f'}).then(()=>location.reload());else setTimeout(()=>location.reload(),1200)}catch(e){busy=false;msg(e.message)}}}timer=setTimeout(tick,180)};b.addEventListener('click',async()=>{try{busy=false;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});v.srcObject=stream;v.hidden=false;x.hidden=false;b.disabled=true;msg('Arahkan kamera ke barcode peserta.');await v.play();tick()}catch(e){msg('Kamera tidak dapat dibuka. Pastikan izin kamera diberikan.')}});x.addEventListener('click',stop)})();
</script>
<?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<div class="row g-3 mb-3">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['Undangan'=>$recap['total'], 'Hadir'=>$recap['present'], ($event->status === 'cancelled' ? 'Dibatalkan / belum hadir' : ($event->isFinished() && $event->status === 'published' ? 'Tidak Hadir' : 'Belum Presensi'))=>$recap['remaining'], 'Kehadiran'=>$recap['percentage'].'%']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label=>$value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?>
<div class="col-6 col-lg-3"><div class="card h-100 mb-0"><div class="card-body"><div class="text-muted"><?php echo e($label); ?></div><strong class="fs-3"><?php echo e($value); ?></strong></div></div></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
</div>
<div class="card"><div class="card-body"><div class="d-flex justify-content-between mb-3"><h3 class="h5">Rekap Kehadiran</h3><a href="<?php echo e(route('admin.bpppmnu.events.export', $event)); ?>" class="btn btn-success btn-sm">Export Excel</a></div>
<div class="table-responsive"><table class="table"><thead><tr><th>Nama</th><th>ID NUIST</th><th>Jabatan</th><th>Status</th><th>Waktu hadir (WIB)</th></tr></thead><tbody>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $recap['rows']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?><tr><td><?php echo e($row->name); ?></td><td><?php echo e($row->nuist_id); ?></td><td><?php echo e($row->jabatan ?: '—'); ?></td><td><?php echo e($row->status); ?></td><td><?php echo e($row->attended_at ?: '—'); ?></td></tr><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><tr><td colspan="5">Belum ada undangan.</td></tr><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</tbody></table></div><small class="text-muted">Muat ulang halaman untuk memperbarui rekap.</small></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.bpppmnu.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/lpmnudiymacpro/Documents/Project Nuist/nuist/resources/views/admin/bpppmnu/show.blade.php ENDPATH**/ ?>