<!doctype html>
<html lang="id">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?php echo e(csrf_token()); ?>">
<title>Presensi <?php echo e($event->name); ?></title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f3f7f5;color:#173d31;font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{width:min(100% - 28px,620px);margin:24px auto}.brand{text-align:center;margin-bottom:18px}.brand img{width:64px;height:64px;object-fit:contain}.brand strong{display:block;margin-top:7px}.card{background:#fff;border:1px solid #dfe9e4;border-radius:18px;padding:22px;box-shadow:0 8px 28px #0b513414;margin-bottom:15px}.event{background:linear-gradient(135deg,#064f3b,#147457);color:#fff}.event h1{font-size:21px;line-height:1.35;margin:5px 0 14px}.event p{margin:5px 0;color:#e3f2eb}.label{font-weight:650;display:block;margin:0 0 7px}.input{width:100%;border:1px solid #cbdad3;border-radius:11px;padding:13px 14px;font:inherit;outline:none}.input:focus{border-color:#08724f;box-shadow:0 0 0 3px #0c7c5620}.results{display:grid;gap:8px;margin-top:10px}.person{width:100%;text-align:left;border:1px solid #dce7e2;background:#fff;border-radius:11px;padding:12px;cursor:pointer}.person:hover,.person.selected{border-color:#08724f;background:#eef8f3}.person strong,.person span{display:block}.person span{font-size:12px;color:#687a72;margin-top:2px}.status{font-size:13px;color:#66766f;margin-top:8px}.tabs{display:flex;gap:7px;margin-bottom:18px}.tab{flex:1;border:1px solid #cbdad3;background:#fff;border-radius:10px;padding:10px;cursor:pointer;font-weight:650}.tab.active{background:#075b43;color:#fff;border-color:#075b43}.field{margin-bottom:15px}.btn{width:100%;border:0;border-radius:12px;padding:14px;background:#075b43;color:#fff;font:inherit;font-weight:700;cursor:pointer}.btn:disabled{opacity:.55;cursor:not-allowed}.notice{border-radius:12px;padding:12px 14px;margin-bottom:14px;background:#fff4d8;color:#735719}.error{background:#fde9e9;color:#8d2424}.hidden{display:none!important}.check{display:flex;gap:9px;align-items:flex-start;margin:16px 0;font-size:13px}.muted{font-size:12px;color:#6c7c75}.spinner{display:none}@media(max-width:420px){.wrap{margin:14px auto}.card{padding:18px}.event h1{font-size:18px}}
</style>
</head>
<body><main class="wrap">
<div class="brand"><img src="<?php echo e(asset('images/logo-maarif-nu.png')); ?>" alt="Logo"><strong>Presensi Kegiatan</strong></div>
<section class="card event"><small><?php echo e($event->type); ?></small><h1><?php echo e($event->name); ?></h1><p>📍 <?php echo e($event->location_name); ?></p><p>🕒 <?php echo e($event->start_at->format('d-m-Y H:i')); ?> WIB</p><p>Presensi ditutup <?php echo e($event->attendance_close_at->format('d-m-Y H:i')); ?> WIB</p></section>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="notice error" role="alert"><?php echo e($errors->first()); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(now()->lt($event->attendance_open_at)): ?><div class="notice">Presensi belum dibuka. Presensi dapat dilakukan mulai <?php echo e($event->attendance_open_at->format('d-m-Y H:i')); ?> WIB.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<?php if(now()->gt($event->attendance_close_at)): ?><div class="notice error">Waktu presensi kegiatan telah berakhir.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<section class="card">
<form method="post" action="<?php echo e(route('public.bpppmnu.store',['token'=>$token])); ?>" id="attendance-form"><?php echo csrf_field(); ?>
<input type="hidden" name="nonce" value="<?php echo e($nonce); ?>"><input type="hidden" name="participant_type" id="participant_type"><input type="hidden" name="invitation_id" id="invitation_id"><input type="hidden" name="guest_invitation_id" id="guest_invitation_id"><input type="hidden" name="latitude" id="latitude"><input type="hidden" name="longitude" id="longitude">
<div class="field"><label class="label" for="participant-search">Cari nama Anda</label><input class="input" id="participant-search" autocomplete="off" maxlength="100" placeholder="Ketik minimal 2 huruf"><div id="search-status" class="status">Hanya nama yang telah didaftarkan admin yang dapat dipilih.</div><div id="participant-results" class="results"></div></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event->allowsRegisteredAttendance()): ?><div id="verification-field" class="field hidden"><label class="label" for="verification"><?php echo e($event->public_name_verification === 'phone_last4' ? '4 digit terakhir nomor HP' : 'ID NUIST / kode peserta'); ?></label><input class="input" id="verification" name="verification" maxlength="50" inputmode="<?php echo e($event->public_name_verification === 'phone_last4' ? 'numeric' : 'text'); ?>"></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<label class="check"><input type="checkbox" id="confirm" required><span>Saya memastikan nama dan data yang saya pilih adalah benar.</span></label><button class="btn" id="submit" <?php if(!now()->betweenIncluded($event->attendance_open_at,$event->attendance_close_at)): echo 'disabled'; endif; ?>>Catat Kehadiran</button><p class="muted">Tidak perlu login. Data hanya digunakan untuk pencatatan kehadiran kegiatan ini.</p>
</form></section></main>
<script>
(()=>{const mode=document.getElementById('participant_type'),form=document.getElementById('attendance-form'),input=document.getElementById('participant-search'),results=document.getElementById('participant-results'),status=document.getElementById('search-status'),registeredId=document.getElementById('invitation_id'),guestId=document.getElementById('guest_invitation_id'),verification=document.getElementById('verification-field'),submit=document.getElementById('submit'),verificationMode=<?php echo json_encode($event->public_name_verification ?: 'none', 15, 512) ?>;let timer,controller;if(input)input.addEventListener('input',()=>{mode.value='';registeredId.value='';guestId.value='';verification?.classList.add('hidden');clearTimeout(timer);controller?.abort();results.innerHTML='';const q=input.value.trim();if(q.length<2){status.textContent='Ketik minimal 2 huruf.';return}status.textContent='Mencari…';timer=setTimeout(async()=>{controller=new AbortController;try{const response=await fetch(<?php echo json_encode(route('public.bpppmnu.participants', ['token'=>$token]), 512) ?>+'?q='+encodeURIComponent(q),{headers:{Accept:'application/json'},signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.message||'Pencarian gagal.');status.textContent=body.data.length?'Pilih nama yang sesuai.':'Nama tidak terdaftar. Hubungi admin kegiatan.';body.data.forEach(person=>{const button=document.createElement('button');button.type='button';button.className='person';button.innerHTML='<strong></strong><span></span>';button.querySelector('strong').textContent=person.name+(person.attended?' · Sudah hadir':'');button.querySelector('span').textContent=[person.position,person.organization].filter(Boolean).join(' · ')||'Peserta undangan';button.disabled=person.attended;button.addEventListener('click',()=>{document.querySelectorAll('.person').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');mode.value=person.type;registeredId.value=person.type==='registered'?person.id:'';guestId.value=person.type==='guest'?person.id:'';verification?.classList.toggle('hidden',person.type!=='registered'||verificationMode==='none');status.textContent='Dipilih: '+person.name});results.appendChild(button)})}catch(error){if(error.name!=='AbortError')status.textContent='Pencarian gagal. Periksa koneksi lalu coba lagi.'}},350)});form.addEventListener('submit',event=>{if(!mode.value||(!registeredId.value&&!guestId.value)){event.preventDefault();status.textContent='Pilih nama Anda terlebih dahulu.';input?.focus();return}submit.disabled=true;submit.textContent='Menyimpan…'});if(navigator.geolocation){navigator.geolocation.getCurrentPosition(position=>{document.getElementById('latitude').value=position.coords.latitude;document.getElementById('longitude').value=position.coords.longitude},()=>{},{enableHighAccuracy:true,timeout:8000,maximumAge:0})}})();
</script></body></html>
<?php /**PATH /Users/lpmnudiymacpro/Documents/Project Nuist/nuist/resources/views/public/bpppmnu-attendance/show.blade.php ENDPATH**/ ?>