<?php $__env->startSection('bpp-content'); ?>
<div class="card"><div class="card-body"><h2 class="h4"><?php echo e($event->exists ? 'Edit' : 'Buat'); ?> Kegiatan</h2>
<p class="text-muted">Seluruh waktu menggunakan WIB. Agenda dan undangan dikunci setelah periode presensi dibuka.</p>
<form method="post" enctype="multipart/form-data" action="<?php echo e($event->exists ? route('admin.bpppmnu.events.update', $event) : route('admin.bpppmnu.events.store')); ?>"><?php echo csrf_field(); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event->exists): ?> <?php echo method_field('PUT'); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
<div class="row g-3">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['name'=>'Nama kegiatan','type'=>'Jenis kegiatan','organizer'=>'Penyelenggara','location_name'=>'Nama lokasi']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?>
<div class="col-md-6"><label class="form-label" for="<?php echo e($field); ?>"><?php echo e($label); ?></label><input class="form-control" id="<?php echo e($field); ?>" name="<?php echo e($field); ?>" value="<?php echo e(old($field, $event->$field)); ?>" maxlength="255" required></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['start_at'=>'Tanggal & waktu mulai','end_at'=>'Tanggal & waktu selesai','attendance_open_at'=>'Presensi dibuka','attendance_close_at'=>'Presensi ditutup']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?>
<div class="col-md-6"><label class="form-label" for="<?php echo e($field); ?>"><?php echo e($label); ?> (WIB)</label><input type="datetime-local" class="form-control" id="<?php echo e($field); ?>" name="<?php echo e($field); ?>" value="<?php echo e(old($field, $event->$field?->format('Y-m-d\TH:i'))); ?>" required></div>
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
<div class="col-md-6"><label class="form-label" for="meeting_url">Link alamat/lokasi kegiatan (opsional)</label><input type="url" class="form-control" id="meeting_url" name="meeting_url" value="<?php echo e(old('meeting_url', $event->meeting_url)); ?>" placeholder="https://maps.google.com/..." aria-describedby="meeting-url-help"><small id="meeting-url-help" class="form-text text-muted">Masukkan link Google Maps atau alamat lokasi kegiatan.</small></div>
<div class="col-md-6"><label class="form-label" for="attachment">Lampiran undangan (PDF/JPG/PNG, maks. 5 MB)</label><input type="file" accept=".pdf,.jpg,.jpeg,.png" class="form-control" id="attachment" name="attachment"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($event->attachment): ?><small>Lampiran saat ini tersimpan. Unggah untuk mengganti.</small><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
<div class="col-12"><fieldset><legend class="h5">Pilih pengurus yang diundang</legend><div style="max-height:320px;overflow:auto" class="border rounded p-3">
<?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $members; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $member): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoop($loop->index); ?><?php endif; ?><div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="invitee-<?php echo e($member->id); ?>" name="invitees[]" value="<?php echo e($member->id); ?>" <?php if(in_array($member->id, old('invitees', $selected))): echo 'checked'; endif; ?>><label class="form-check-label" for="invitee-<?php echo e($member->id); ?>"><?php echo e($member->name); ?> · <?php echo e($member->nuist_id); ?> · <?php echo e($member->ketugasan); ?></label></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><p>Belum ada akun pengurus aktif. Buat akun melalui menu Pengurus BPPPMNU.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div></fieldset></div>
<div class="col-12"><button class="btn btn-primary"><?php echo e($event->exists ? 'Simpan Perubahan' : 'Simpan Draft'); ?></button></div>
</div></form></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.bpppmnu.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/lpmnudiymacpro/Documents/Project Nuist/nuist/resources/views/admin/bpppmnu/form.blade.php ENDPATH**/ ?>