@extends('admin.bpppmnu.layout')
@section('bpp-content')
<div class="d-flex justify-content-between align-items-center mb-4 gap-2"><div><h2 class="h4 mb-1">{{ $event->exists ? 'Edit Agenda' : 'Buat Agenda Baru' }}</h2><p class="text-muted mb-0">Lengkapi informasi kegiatan dan pilih peserta yang diundang.</p></div><a href="{{ route('admin.bpppmnu.events.index') }}" class="btn btn-light">Kembali</a></div>
<form method="post" enctype="multipart/form-data" action="{{ $event->exists ? route('admin.bpppmnu.events.update', $event) : route('admin.bpppmnu.events.store') }}">
@csrf @if($event->exists) @method('PUT') @endif
<div class="card mb-3"><div class="card-header bg-white"><h3 class="h6 mb-0"><i class="bx bx-calendar-event me-2 text-primary"></i>Informasi Kegiatan</h3></div><div class="card-body"><div class="row g-3">
@foreach(['name'=>'Nama kegiatan','type'=>'Jenis kegiatan','organizer'=>'Penyelenggara','location_name'=>'Nama lokasi'] as $field=>$label)<div class="col-md-6"><label class="form-label" for="{{ $field }}">{{ $label }} <span class="text-danger">*</span></label><input class="form-control" id="{{ $field }}" name="{{ $field }}" value="{{ old($field, $event->$field) }}" maxlength="255" required></div>@endforeach
<div class="col-12"><label class="form-label" for="meeting_url">Link alamat/lokasi kegiatan <span class="text-muted fw-normal">(opsional)</span></label><input type="url" class="form-control" id="meeting_url" name="meeting_url" value="{{ old('meeting_url', $event->meeting_url) }}" placeholder="https://maps.google.com/..."><div class="form-text">Gunakan link Google Maps agar lokasi mudah dibuka.</div></div>
</div></div></div>
<div class="card mb-3"><div class="card-header bg-white"><h3 class="h6 mb-0"><i class="bx bx-time-five me-2 text-primary"></i>Jadwal Kegiatan dan Presensi</h3></div><div class="card-body"><div class="row g-3">
@foreach(['start_at'=>'Tanggal & waktu mulai','end_at'=>'Tanggal & waktu selesai','attendance_open_at'=>'Presensi dibuka','attendance_close_at'=>'Presensi ditutup'] as $field=>$label)<div class="col-md-6"><label class="form-label" for="{{ $field }}">{{ $label }} <span class="text-danger">*</span></label><input type="datetime-local" class="form-control" id="{{ $field }}" name="{{ $field }}" value="{{ old($field, $event->$field?->format('Y-m-d\TH:i')) }}" required><div class="form-text">Waktu Indonesia Barat (WIB).</div></div>@endforeach
</div></div></div>
<div class="card mb-3"><div class="card-header bg-white"><h3 class="h6 mb-0"><i class="bx bx-file me-2 text-primary"></i>Lampiran</h3></div><div class="card-body"><label class="form-label" for="attachment">Lampiran undangan <span class="text-muted fw-normal">(opsional, PDF/JPG/PNG maksimal 5 MB)</span></label><input type="file" accept=".pdf,.jpg,.jpeg,.png" class="form-control" id="attachment" name="attachment">@if($event->attachment)<div class="form-text text-success">Lampiran saat ini tersimpan. Upload file baru untuk menggantinya.</div>@endif</div></div>
<div class="card mb-4"><div class="card-header bg-white d-flex justify-content-between align-items-center"><div><h3 class="h6 mb-1"><i class="bx bx-group me-2 text-primary"></i>Peserta Undangan</h3><p class="text-muted small mb-0">Hanya member BPPPMNU aktif yang dapat diundang.</p></div><span class="badge bg-light text-dark">{{ $members->count() }} member aktif</span></div><div class="card-body"><div class="border rounded p-3" style="max-height:340px;overflow:auto">@forelse($members as $member)<div class="form-check py-2 border-bottom"><input class="form-check-input" type="checkbox" id="invitee-{{ $member->id }}" name="invitees[]" value="{{ $member->id }}" @checked(in_array($member->id, old('invitees', $selected)))><label class="form-check-label" for="invitee-{{ $member->id }}"><strong>{{ $member->name }}</strong><span class="d-block text-muted small">{{ $member->bpppmnuMember?->jabatan ?: 'Pengurus BPPPMNU' }} · {{ $member->email }}</span></label></div>@empty<p class="text-muted mb-0">Belum ada member BPPPMNU aktif.</p>@endforelse</div></div></div>
<div class="d-flex justify-content-end gap-2 mb-4"><a href="{{ route('admin.bpppmnu.events.index') }}" class="btn btn-light">Batal</a><button class="btn btn-primary px-4"><i class="bx bx-save me-1"></i>{{ $event->exists ? 'Simpan Perubahan' : 'Simpan sebagai Draft' }}</button></div>
</form>
@endsection
