@extends('admin.bpppmnu.layout')
@section('bpp-content')
<div class="d-flex justify-content-between align-items-center mb-4 gap-2"><div><h2 class="h4 mb-1">{{ $event->exists ? 'Edit Agenda' : 'Buat Agenda Baru' }}</h2><p class="text-muted mb-0">Lengkapi informasi kegiatan dan pilih peserta yang diundang.</p></div><a href="{{ route('admin.agenda.index') }}" class="btn btn-light">Kembali</a></div>
<form method="post" enctype="multipart/form-data" action="{{ $event->exists ? route('admin.agenda.update', $event) : route('admin.agenda.store') }}">
@csrf @if($event->exists) @method('PUT') @endif
<div class="card mb-3"><div class="card-header bg-white"><h3 class="h6 mb-0"><i class="bx bx-calendar-event me-2 text-primary"></i>Informasi Kegiatan</h3></div><div class="card-body"><div class="row g-3">
@foreach(['name'=>'Nama kegiatan','type'=>'Jenis kegiatan','organizer'=>'Penyelenggara','location_name'=>'Nama lokasi'] as $field=>$label)<div class="col-md-6"><label class="form-label" for="{{ $field }}">{{ $label }} <span class="text-danger">*</span></label><input class="form-control" id="{{ $field }}" name="{{ $field }}" value="{{ old($field, $event->$field) }}" maxlength="255" required></div>@endforeach
<div class="col-12"><label class="form-label" for="meeting_url">Link alamat/lokasi kegiatan <span class="text-muted fw-normal">(opsional)</span></label><input type="url" class="form-control" id="meeting_url" name="meeting_url" value="{{ old('meeting_url', $event->meeting_url) }}" placeholder="https://maps.google.com/..."><div class="form-text">Gunakan link Google Maps agar lokasi mudah dibuka.</div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="location_validation_enabled" value="1" id="location_validation_enabled" @checked(old('location_validation_enabled',$event->location_validation_enabled))><label class="form-check-label" for="location_validation_enabled">Aktifkan validasi lokasi presensi</label></div></div><div class="col-md-4"><label class="form-label">Latitude</label><input class="form-control" name="latitude" value="{{ old('latitude',$event->latitude) }}"></div><div class="col-md-4"><label class="form-label">Longitude</label><input class="form-control" name="longitude" value="{{ old('longitude',$event->longitude) }}"></div><div class="col-md-4"><label class="form-label">Radius (meter)</label><input class="form-control" type="number" min="10" max="1000" name="location_radius_meters" value="{{ old('location_radius_meters',$event->location_radius_meters ?: 50) }}"></div>
</div></div></div>
<div class="card mb-3"><div class="card-header bg-white"><h3 class="h6 mb-0"><i class="bx bx-qr me-2 text-primary"></i>Akses Presensi Publik</h3></div><div class="card-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label" for="attendance_access_mode">Peserta yang diizinkan</label><select class="form-select" id="attendance_access_mode" name="attendance_access_mode" required>@foreach(['registered'=>'Peserta terdaftar saja','hybrid'=>'Peserta terdaftar + tamu','guest'=>'Tamu saja'] as $value=>$label)<option value="{{ $value }}" @selected(old('attendance_access_mode',$event->attendance_access_mode ?: 'registered')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label" for="public_name_verification">Verifikasi peserta terdaftar</label><select class="form-select" id="public_name_verification" name="public_name_verification" required>@foreach(['none'=>'Konfirmasi nama saja','phone_last4'=>'4 digit terakhir nomor HP','participant_code'=>'ID NUIST / kode peserta'] as $value=>$label)<option value="{{ $value }}" @selected(old('public_name_verification',$event->public_name_verification ?: 'none')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label" for="capacity">Kapasitas hadir <span class="text-muted">(opsional)</span></label><input class="form-control" type="number" min="1" max="100000" id="capacity" name="capacity" value="{{ old('capacity',$event->capacity) }}"></div>
<div class="col-md-4 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="guest_phone_required" value="1" id="guest_phone_required" @checked(old('guest_phone_required',$event->guest_phone_required))><label class="form-check-label" for="guest_phone_required">Nomor HP tamu wajib</label></div></div>
<div class="col-md-4 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="guest_organization_required" value="1" id="guest_organization_required" @checked(old('guest_organization_required',$event->guest_organization_required))><label class="form-check-label" for="guest_organization_required">Instansi tamu wajib</label></div></div>
</div><div class="form-text mt-3">QR membuka halaman web tanpa login. Untuk kegiatan resmi, gunakan verifikasi 4 digit nomor HP atau kode peserta.</div></div></div>
<div class="card mb-3"><div class="card-header bg-white"><h3 class="h6 mb-0"><i class="bx bx-time-five me-2 text-primary"></i>Jadwal Kegiatan dan Presensi</h3></div><div class="card-body"><div class="row g-3">
@foreach(['start_at'=>'Tanggal & waktu mulai','end_at'=>'Tanggal & waktu selesai','attendance_open_at'=>'Presensi dibuka','attendance_close_at'=>'Presensi ditutup'] as $field=>$label)<div class="col-md-6"><label class="form-label" for="{{ $field }}">{{ $label }} <span class="text-danger">*</span></label><input type="datetime-local" class="form-control" id="{{ $field }}" name="{{ $field }}" value="{{ old($field, $event->$field?->format('Y-m-d\TH:i')) }}" required><div class="form-text">Waktu Indonesia Barat (WIB).</div></div>@endforeach
</div></div></div>
<div class="card mb-3"><div class="card-header bg-white"><h3 class="h6 mb-0"><i class="bx bx-file me-2 text-primary"></i>Lampiran</h3></div><div class="card-body"><label class="form-label" for="attachment">Lampiran undangan <span class="text-muted fw-normal">(opsional, PDF/JPG/PNG maksimal 5 MB)</span></label><input type="file" accept=".pdf,.jpg,.jpeg,.png" class="form-control" id="attachment" name="attachment">@if($event->attachment)<div class="form-text text-success">Lampiran saat ini tersimpan. Upload file baru untuk menggantinya.</div>@endif</div></div>
<div class="card mb-4"><div class="card-header bg-white d-flex justify-content-between align-items-center"><div><h3 class="h6 mb-1"><i class="bx bx-group me-2 text-primary"></i>Peserta Undangan Terdaftar</h3><p class="text-muted small mb-0">Cari dan pilih pengguna aktif dari seluruh unit.</p></div><span class="badge bg-light text-dark">{{ $members->count() }} pengguna aktif</span></div><div class="card-body"><label class="form-label" for="invitee-search">Cari nama peserta</label><div class="input-group mb-3"><span class="input-group-text"><i class="bx bx-search"></i></span><input type="search" class="form-control" id="invitee-search" placeholder="Ketik nama, jabatan, instansi, atau email…" autocomplete="off"></div><div class="d-flex justify-content-between align-items-center mb-3"><div class="form-check"><input class="form-check-input" type="checkbox" id="select-all-invitees"><label class="form-check-label fw-semibold" for="select-all-invitees">Pilih semua hasil pencarian</label></div><span id="invitee-result-count" class="small text-muted"></span></div><div id="invitee-list" class="border rounded p-3" style="max-height:340px;overflow:auto">@forelse($members as $member)<div class="form-check py-2 border-bottom invitee-row" data-search="{{ Str::lower($member->name.' '.($member->bpppmnuMember?->jabatan ?: $member->jabatan).' '.($member->madrasah?->name ?: $member->instansi_asal).' '.$member->email) }}"><input class="form-check-input invitee-checkbox" type="checkbox" id="invitee-{{ $member->id }}" name="invitees[]" value="{{ $member->id }}" @checked(in_array($member->id, old('invitees', $selected)))><label class="form-check-label" for="invitee-{{ $member->id }}"><strong>{{ $member->name }}</strong><span class="d-block text-muted small">{{ $member->bpppmnuMember?->jabatan ?: ($member->jabatan ?: ($member->ketugasan ?: ucfirst(str_replace('_',' ',$member->role)))) }} · {{ $member->madrasah?->name ?: ($member->instansi_asal ?: $member->email) }}</span></label></div>@empty<p class="text-muted mb-0">Belum ada pengguna aktif.</p>@endforelse<div id="invitee-no-result" class="text-muted text-center py-3 d-none">Nama peserta tidak ditemukan.</div></div></div></div>
@php($guestRows = collect(old('guest_invitees', $guestInvitees->map(fn($guest) => ['id'=>$guest->id,'name'=>$guest->name,'organization'=>$guest->organization,'phone'=>$guest->phone])->all())))
<div class="card mb-4" id="guest-invitations-card"><div class="card-header bg-white d-flex justify-content-between align-items-center gap-2 flex-wrap"><div><h3 class="h6 mb-1"><i class="bx bx-user-plus me-2 text-primary"></i>Tamu Undangan Tambahan</h3><p class="text-muted small mb-0">Masukkan tamu secara manual satu per satu atau import banyak nama dari Excel.</p></div><button class="btn btn-sm btn-primary" type="button" id="add-guest"><i class="bx bx-plus me-1"></i>Input Tamu Manual</button></div><div class="card-body"><div class="border rounded p-3 mb-3 bg-light"><div class="row g-3 align-items-end"><div class="col-md-8"><label class="form-label" for="guest_import">Import banyak tamu dari Excel <span class="text-muted fw-normal">(opsional)</span></label><input type="file" class="form-control" id="guest_import" name="guest_import" accept=".xlsx,.xls,.csv"><div class="form-text">Format: Nama, Instansi, Nomor HP. Maksimal 5 MB dan 5.000 tamu.</div></div><div class="col-md-4"><a class="btn btn-outline-success w-100" href="{{ route('admin.agenda.guest-import-template') }}"><i class="bx bx-download me-1"></i>Unduh Template Excel</a></div></div></div><div class="d-flex justify-content-between align-items-center mb-2"><h4 class="h6 mb-0">Daftar input manual</h4><span class="small text-muted">Nama dapat ditambahkan tanpa file Excel</span></div><div id="guest-rows" class="d-grid gap-2">@foreach($guestRows as $index=>$guest)<div class="guest-row border rounded p-3"><input type="hidden" data-field="id" name="guest_invitees[{{ $index }}][id]" value="{{ $guest['id'] ?? '' }}"><div class="row g-2"><div class="col-md-4"><label class="form-label">Nama lengkap</label><input class="form-control" data-field="name" name="guest_invitees[{{ $index }}][name]" value="{{ $guest['name'] ?? '' }}" maxlength="255"></div><div class="col-md-3"><label class="form-label">Instansi</label><input class="form-control" data-field="organization" name="guest_invitees[{{ $index }}][organization]" value="{{ $guest['organization'] ?? '' }}" maxlength="255"></div><div class="col-md-3"><label class="form-label">Nomor HP</label><input class="form-control" data-field="phone" name="guest_invitees[{{ $index }}][phone]" value="{{ $guest['phone'] ?? '' }}" maxlength="30"></div><div class="col-md-2 d-flex align-items-end"><button type="button" class="btn btn-outline-danger w-100 remove-guest">Hapus</button></div></div></div>@endforeach</div><div id="guest-empty" class="text-muted small {{ $guestRows->isNotEmpty() ? 'd-none' : '' }}">Belum ada input manual. Klik tombol “Input Tamu Manual” untuk menambahkan nama.</div></div></div>
<div class="d-flex justify-content-end gap-2 mb-4"><a href="{{ route('admin.agenda.index') }}" class="btn btn-light">Batal</a><button class="btn btn-primary px-4"><i class="bx bx-save me-1"></i>{{ $event->exists ? 'Simpan Perubahan' : 'Simpan sebagai Draft' }}</button></div>
</form>
<template id="guest-row-template"><div class="guest-row border rounded p-3"><div class="row g-2"><div class="col-md-4"><label class="form-label">Nama lengkap</label><input class="form-control" data-field="name" maxlength="255"></div><div class="col-md-3"><label class="form-label">Instansi</label><input class="form-control" data-field="organization" maxlength="255"></div><div class="col-md-3"><label class="form-label">Nomor HP</label><input class="form-control" data-field="phone" maxlength="30"></div><div class="col-md-2 d-flex align-items-end"><button type="button" class="btn btn-outline-danger w-100 remove-guest">Hapus</button></div></div></div></template>
<script>document.addEventListener('DOMContentLoaded',function(){const all=document.getElementById('select-all-invitees'),items=[...document.querySelectorAll('.invitee-checkbox')],inviteeRows=[...document.querySelectorAll('.invitee-row')],search=document.getElementById('invitee-search'),resultCount=document.getElementById('invitee-result-count'),noResult=document.getElementById('invitee-no-result'),mode=document.getElementById('attendance_access_mode'),rows=document.getElementById('guest-rows'),empty=document.getElementById('guest-empty'),template=document.getElementById('guest-row-template');const visibleItems=()=>inviteeRows.filter(row=>!row.classList.contains('d-none')).map(row=>row.querySelector('.invitee-checkbox'));const sync=()=>{const visible=visibleItems();if(all){all.checked=visible.length>0&&visible.every(i=>i.checked);all.indeterminate=visible.some(i=>i.checked)&&!all.checked}items.forEach(i=>i.required=false);resultCount.textContent=`${visible.length} nama ditemukan`;noResult.classList.toggle('d-none',visible.length>0)};search?.addEventListener('input',()=>{const needle=search.value.trim().toLocaleLowerCase('id-ID');inviteeRows.forEach(row=>row.classList.toggle('d-none',needle!==''&&!row.dataset.search.includes(needle)));sync()});all?.addEventListener('change',()=>visibleItems().forEach(i=>i.checked=all.checked));items.forEach(i=>i.addEventListener('change',sync));mode?.addEventListener('change',sync);const reindex=()=>{[...rows.querySelectorAll('.guest-row')].forEach((row,index)=>row.querySelectorAll('[data-field]').forEach(input=>input.name=`guest_invitees[${index}][${input.dataset.field}]`));empty.classList.toggle('d-none',rows.children.length>0)};rows.addEventListener('click',event=>{if(event.target.closest('.remove-guest')){event.target.closest('.guest-row').remove();reindex()}});document.getElementById('add-guest').addEventListener('click',()=>{if(mode.value==='registered')mode.value='hybrid';rows.appendChild(template.content.cloneNode(true));reindex();rows.lastElementChild.querySelector('[data-field="name"]').focus()});sync();reindex();});</script>
@endsection
