@extends('admin.bpppmnu.layout')
@section('bpp-content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card mb-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><h4 class="card-title mb-0"><i class="bx bx-group me-2"></i>Pengurus BPPPMNU</h4><div class="d-flex flex-wrap gap-2"><a class="btn btn-danger" href="{{ route('admin.bpppmnu.members.export-pdf') }}"><i class="bx bxs-file-pdf me-1"></i>Export PDF</a><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalTambahPengurus">Tambah Pengurus</button><button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modalImportPengurus">Import Data</button></div></div></div></div>
<div class="card"><div class="card-body"><div class="table-responsive"><table id="datatable-buttons" class="table table-bordered dt-responsive nowrap w-100"><thead class="table-light"><tr><th>No</th><th>Nama</th><th>Jabatan</th><th>Instansi Asal</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($members as $index => $member)<tr><td>{{ $members->firstItem() + $index }}</td><td>{{ $member->name }}</td><td>{{ $member->bpppmnu_jabatan ?: $member->jabatan ?: $member->ketugasan ?: '—' }}</td><td>{{ $member->bpppmnu_instansi_asal ?: ($member->instansi_asal ?: ($member->madrasah?->name ?: '—')) }}</td><td>{{ $member->email }}</td><td>{{ $member->is_active ? 'Aktif' : 'Nonaktif' }}</td><td><button class="btn btn-sm btn-warning" data-bs-toggle="modal" data-bs-target="#modalEditPengurus{{ $member->id }}">Edit</button> <form class="d-inline" method="post" action="{{ route('admin.bpppmnu.members.destroy', $member) }}" onsubmit="return confirm('Hapus pengurus ini? Jika akun tenaga pendidik, akun akan dinonaktifkan.')">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-danger">Hapus</button></form></td></tr>
@empty<tr><td colspan="7">Belum ada pengurus BPPPMNU.</td></tr>@endforelse
</tbody></table></div>{{ $members->links('pagination::bootstrap-5') }}</div></div>
<div class="modal fade" id="modalTambahPengurus" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Tambah Pengurus BPPPMNU</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form method="post" action="{{ route('admin.bpppmnu.members.store') }}"><div class="modal-body">@csrf @include('admin.bpppmnu.member-fields', ['member'=>null])</div></form></div></div></div>
<div class="modal fade" id="modalImportPengurus" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" enctype="multipart/form-data" action="{{ route('admin.bpppmnu.members.import') }}"><div class="modal-header"><h5 class="modal-title">Import Data Pengurus</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@csrf<label class="form-label">File Excel/CSV</label><input class="form-control" type="file" name="file" accept=".xlsx,.xls,.csv" required><small class="text-muted">Kolom: nama, jabatan, instansi_asal, email (opsional).</small></div><div class="modal-footer"><button class="btn btn-success">Import Data</button></div></form></div></div></div>
@foreach($members as $member)<div class="modal fade" id="modalEditPengurus{{ $member->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Edit Pengurus</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form method="post" action="{{ route('admin.bpppmnu.members.update', $member) }}"><div class="modal-body">@csrf @method('PUT') @include('admin.bpppmnu.member-fields')</div></form></div></div></div>@endforeach
@endsection
