<div class="row g-2">
@if(!$member?->exists && isset($teachers))
<div class="col-12"><label class="form-label" for="existing_user_id">Pilih akun tenaga pendidik yang sudah ada (opsional)</label><select class="form-select" id="existing_user_id" name="existing_user_id" onchange="bppFillTeacher(this)"><option value="">Tambah akun baru</option>@foreach($teachers as $teacher)@php($schoolName = optional($teacher->madrasah)->name ?: $teacher->instansi_asal)<option value="{{ $teacher->id }}" data-name="{{ $teacher->name }}" data-email="{{ $teacher->email }}" data-jabatan="{{ $teacher->jabatan ?: $teacher->ketugasan }}" data-instansi="{{ $schoolName }}">{{ $teacher->name }} · {{ $teacher->email }} · {{ $schoolName ?: 'Madrasah belum diatur' }}</option>@endforeach</select><small class="text-muted">Instansi asal otomatis mengambil nama madrasah/sekolah akun tenaga pendidik.</small></div>
@endif
@foreach(['name'=>'Nama','email'=>'Email','jabatan'=>'Jabatan','instansi_asal'=>'Instansi Asal'] as $field=>$label)
<div class="col-md-6"><label class="form-label" for="member-{{ $member?->id ?? 'new' }}-{{ $field }}">{{ $label }}</label><input id="member-{{ $member?->id ?? 'new' }}-{{ $field }}" name="{{ $field }}" type="{{ $field === 'email' ? 'email' : 'text' }}" class="form-control" value="{{ $member?->$field }}" @required(in_array($field,['name','email']))></div>
@endforeach
<div class="col-md-6"><label class="form-label">Status akun<select name="is_active" class="form-select"><option value="1" @selected(!$member || $member->is_active)>Aktif</option><option value="0" @selected($member && !$member->is_active)>Nonaktif</option></select></label></div>
<div class="col-md-6 password-fields"><label class="form-label">{{ $member ? 'Reset password (kosongkan jika tetap)' : 'Password awal' }}<input name="password" type="password" class="form-control" autocomplete="new-password" minlength="8" @required(!$member)></label></div>
<div class="col-md-6 password-fields"><label class="form-label">Konfirmasi password<input name="password_confirmation" type="password" class="form-control" autocomplete="new-password" minlength="8" @required(!$member)></label></div>
<div class="col-12"><small class="text-muted">Password minimal 8 karakter: huruf besar, huruf kecil, angka, dan simbol (@$!%*?&).</small></div>
<div class="col-12"><button class="btn btn-primary mt-2">Simpan Pengurus</button></div></div>
@if(!$member?->exists && isset($teachers))<script>window.bppFillTeacher=function(select){const o=select.options[select.selectedIndex];['name','email','jabatan','instansi_asal'].forEach(f=>{const i=document.getElementById('member-new-'+f);if(i)i.value=o?.dataset?.[f]||'';});document.querySelectorAll('.password-fields input').forEach(i=>{i.required=!select.value;i.closest('.password-fields').style.display=select.value?'none':'';});};</script>@endif
