<?php

use App\Models\Siswa;
use App\Services\StudentDefaultPasswordService;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Hash;

return new class extends Migration
{
    /**
     * Convert only the password generated by the first rollout migration.
     * Passwords independently changed by a student or administrator stay put.
     */
    public function up(): void
    {
        $service = app(StudentDefaultPasswordService::class);

        Siswa::query()
            ->where('is_active', true)
            ->whereNotNull('nisn')
            ->whereNotNull('tanggal_lahir')
            ->whereNotNull('password')
            ->orderBy('id')
            ->eachById(function (Siswa $siswa) use ($service) {
                if (Hash::check('Nuist14082026', $siswa->password)) {
                    $service->resetToDefault($siswa);
                }
            });
    }

    public function down(): void
    {
        // Never restore a weaker date-of-creation password on rollback.
    }
};
