<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('teaching_attendances')) {
            return;
        }

        $hasAttendanceSource = Schema::hasColumn('teaching_attendances', 'attendance_source');
        $hasStatusLabel = Schema::hasColumn('teaching_attendances', 'status_label');
        $hasCalendarEventId = Schema::hasColumn('teaching_attendances', 'academic_calendar_event_id');
        $hasAutoGenerated = Schema::hasColumn('teaching_attendances', 'is_auto_generated');

        Schema::table('teaching_attendances', function (Blueprint $table) use (
            $hasAttendanceSource,
            $hasStatusLabel,
            $hasCalendarEventId,
            $hasAutoGenerated
        ) {
            if (!$hasAttendanceSource) {
                $table->string('attendance_source', 50)->default('manual')->after('status');
            }

            if (!$hasStatusLabel) {
                $table->string('status_label')->nullable()->after('attendance_source');
            }

            if (!$hasCalendarEventId) {
                $table->unsignedBigInteger('academic_calendar_event_id')->nullable()->after('status_label');
            }

            if (!$hasAutoGenerated) {
                $table->boolean('is_auto_generated')->default(false)->after('academic_calendar_event_id');
            }
        });

        if (!$hasCalendarEventId) {
            Schema::table('teaching_attendances', function (Blueprint $table) {
                $table->foreign('academic_calendar_event_id', 'teaching_attendances_calendar_event_fk')
                    ->references('id')
                    ->on('academic_calendar_events')
                    ->nullOnDelete();
            });
        }
    }

    public function down(): void
    {
        if (!Schema::hasTable('teaching_attendances')) {
            return;
        }

        $hasCalendarEventId = Schema::hasColumn('teaching_attendances', 'academic_calendar_event_id');
        $hasAutoGenerated = Schema::hasColumn('teaching_attendances', 'is_auto_generated');
        $hasStatusLabel = Schema::hasColumn('teaching_attendances', 'status_label');
        $hasAttendanceSource = Schema::hasColumn('teaching_attendances', 'attendance_source');

        Schema::table('teaching_attendances', function (Blueprint $table) use (
            $hasCalendarEventId,
            $hasAutoGenerated,
            $hasStatusLabel,
            $hasAttendanceSource
        ) {
            if ($hasCalendarEventId) {
                $table->dropForeign('teaching_attendances_calendar_event_fk');
                $table->dropColumn('academic_calendar_event_id');
            }

            if ($hasAutoGenerated) {
                $table->dropColumn('is_auto_generated');
            }

            if ($hasStatusLabel) {
                $table->dropColumn('status_label');
            }

            if ($hasAttendanceSource) {
                $table->dropColumn('attendance_source');
            }
        });
    }
};
